version: '3.8'
services:
  identity:
    build: .
    container_name: identity_service
    volumes:
      - ./services/identity-service:/srv
    working_dir: /srv
    command: sh -c "npm install && node index.js"
    ports:
      - "4100:4100"

  location:
    build: .
    container_name: location_ingest
    volumes:
      - ./services/location-ingest:/srv
    working_dir: /srv
    command: sh -c "npm install && node index.js"
    ports:
      - "4000:4000"

  anomaly:
    build: .
    container_name: anomaly_service
    volumes:
      - ./services/anomaly-service:/srv
    working_dir: /srv
    command: sh -c "npm install && node consumer.js"
    environment:
      - LOCATION_SERVICE=http://location:4000
